// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkdg1TQHHNKshp0daD79tyF8t9eTQKS3c',
    appId: '1:103420883794:android:2999cebe3c17a41231008b',
    messagingSenderId: '103420883794',
    projectId: 'smart-app-e0e21',
    authDomain: 'smart-app-e0e21-default-rtdb.firebaseio.com',
    storageBucket: 'smart-app-e0e21.appspot.com'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkdg1TQHHNKshp0daD79tyF8t9eTQKS3c',
    appId: '1:103420883794:android:2999cebe3c17a41231008b',
    messagingSenderId: '103420883794',
    projectId: 'smart-app-e0e21',
    storageBucket: 'smart-app-e0e21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0HN7lma_h39jWlT8wPIjXQ5gOmbYZrhE',
    appId: '1:103420883794:android:2999cebe3c17a41231008b',
    messagingSenderId: '103420883794',
    projectId: 'shopy-app-b3ca4',
    storageBucket: 'authtutorial-de80c.appspot.com',
    iosClientId: '637905690799-9shnm980f8q6vjk9rbq6eih4tfp1l7jg.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0HN7lma_h39jWlT8wPIjXQ5gOmbYZrhE',
    appId: '1:103420883794:android:2999cebe3c17a41231008b',
    messagingSenderId: '103420883794',
    projectId: 'shopy-app-b3ca4',
    storageBucket: 'authtutorial-de80c.appspot.com',
    iosClientId: '637905690799-9shnm980f8q6vjk9rbq6eih4tfp1l7jg.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}




